version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: deathnote-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  frontend:
    build:
      context: ./frontend
    container_name: deathnote-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000  # Usar el nombre del servicio backend

  db:
    image: postgres:bookworm
    container_name: deathnote-db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pg-data: